language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    - IMAGE=kazakovdu/content-storage
    - TAG=${TRAVIS_TAG:-latest}

jobs:
  include:
    - stage: waiting_db
      name: Waiting for PostgreSQL to be ready
      command: |
        for i in `seq 1 10`;
        do
          nc -z db 3306 && echo Success && exit 0
          echo -n .
          sleep 1
        done
        echo PostgreSQL has not been started && exit 1

    - stage: test
      name: "Run linters and tests"
      install: pip install -r requirements/dev.txt
      before_script: cp example.env .env
      script: make qa
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: build
      name: "Build a docker image"
      install: skip
      script: docker build -t $IMAGE:$TAG .

stages:
  - test
  - name: build
    if: tag IS blank
