---

version: '3.8'

x-env-defaults: &defaults
  restart: always
  env_file: .env
  environment:
    DB_HOST: db
    BROKER_HOST: redis

services:

  runserver:
    <<: *defaults
    build:
      context: .
      target: production
    image: kazakovdu/content-storage:latest
    container_name: django
    command: make production
    volumes:
      - $VOLUMES_DIR/public:/opt/app/content_storage/public
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    <<: *defaults
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - $DB_PORT:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    <<: *defaults
    image: redis:6-alpine
    ports:
      - $BROKER_PORT:6379
    volumes:
      - redis:/data

  nginx:
    <<: *defaults
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - $VOLUMES_DIR/public:/var/www/public
    depends_on:
      - runserver

volumes:
  postgres:
  redis:
