# Generated by Django 3.2.3 on 2021-05-30 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Page',
                'default_related_name': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Title')),
                ('counter', models.PositiveBigIntegerField(default=0, verbose_name='Counter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('source', models.FileField(upload_to='videos', verbose_name='File')),
                ('subtitles', models.FileField(upload_to='subtitles', verbose_name='Subtitles')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.page')),
            ],
            options={
                'verbose_name': 'Video',
                'ordering': ('-created_at',),
                'abstract': False,
                'default_related_name': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Title')),
                ('counter', models.PositiveBigIntegerField(default=0, verbose_name='Counter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content', models.TextField(verbose_name='File')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='content.page')),
            ],
            options={
                'verbose_name': 'Text',
                'ordering': ('-created_at',),
                'abstract': False,
                'default_related_name': 'texts',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Title')),
                ('counter', models.PositiveBigIntegerField(default=0, verbose_name='Counter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('source', models.FileField(upload_to='audios', verbose_name='File')),
                ('bit_rate', models.PositiveIntegerField(verbose_name='Bit rate')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='content.page')),
            ],
            options={
                'verbose_name': 'Audio',
                'ordering': ('-created_at',),
                'abstract': False,
                'default_related_name': 'audios',
            },
        ),
    ]
